- name: setup a website on linux server
  host:
  become: yes
  tasks:
    - name: install appache
      yum: 
      name: httpd
      state: present
    - name: httpd
      services: present
        name: start
        state: started
        enabled: true
    - name: copy a file into /var/www/html
      shell: cd /var/www/html && echo "hello world" > index.html
      

